# Generated by Django 3.0.8 on 2020-07-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
